
# Config file for Alpaca API
#
# This file should contain the user-specific configuration parameters
# for the Alpaca API, such as API keys.

# The base URL of the Alpaca API
base_url: https://paper-api.alpaca.markets

# Your Alpaca API key ID
api_key: <Your-API-Key-Here>

# Your Alpaca secret key
secret_key: <Your-Secret-Key-Here>

# Whether or not to use Polygon for data.
polygon: false
